MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://Caffe2Detectron/COCO/36494496/e2e_mask_rcnn_X-101-64x4d-FPN_1x"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    FREEZE_CONV_BODY_AT: 2
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (8, 16, 32, 64, 128)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 4000
    PRE_NMS_TOP_N_TEST: 4000
    # POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_PER_BATCH: False
    PRED_TARGETS: True
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 1000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # CONV_LAYERS: (256, 256, 256, 256, 256)
  MASK_ON: True
  FPN:
    USE_DA: True
DATASETS:
  TRAIN: ("DH100_2019_train_cocostyle",)
  TEST: ("DH100_2019_test_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  # epoch 30 50 75 so 1800, 3000, 4500
  STEPS: (1000,)
  MAX_ITER: 1000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 50
# OUTPUT_DIR: "/media/fs3017/eeum/nuclei/outputs/outputs_DH100_baseline_da_pt"
OUTPUT_DIR: "/home/feng/data/outputs/outputs_DH100_baseline_da_pt"
INPUT:
  MIN_SIZE_TRAIN: (360,)
  MIN_SIZE_TEST: 360
  VERTICAL_FLIP_PROB_TRAIN: 0.5
  PIXEL_MEAN: [48.22, 39.56, 43.53]
  AUG: False
